// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartScaleMinimalAPI;

#nullable disable

namespace SmartScaleMinimalApi.Migrations
{
    [DbContext(typeof(SmartScaleDb))]
    [Migration("20230203081409_updateCtimeTypeFromIntToLong")]
    partial class updateCtimeTypeFromIntToLong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartScaleMinimalAPI.SmartScale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Ctime")
                        .HasColumnType("bigint");

                    b.Property<string>("FaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaceNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GatewayId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Scales");
                });

            modelBuilder.Entity("SmartScaleMinimalApi.FaceEigen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Ctime")
                        .HasColumnType("bigint");

                    b.Property<string>("Eigen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaceNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GatewayId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FaceEigens");
                });

            modelBuilder.Entity("SmartScaleMinimalApi.PersonInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<float?>("Beauty")
                        .HasColumnType("real");

                    b.Property<long>("Ctime")
                        .HasColumnType("bigint");

                    b.Property<string>("FaceNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GatewayId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FaceNo")
                        .IsUnique();

                    b.ToTable("PersonInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
